version: '3'
networks:
  dev:
    driver: bridge
services:
  api:
    container_name: server
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - dev
    ports:
      - 8090:8090
  web:
    container_name: client
    build:
      context: ./web
      dockerfile: Dockerfile
    networks:
      - dev
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - ./web:/app
    depends_on:
      - api